apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-x1
  name: web-x1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web-x1
  template:
    metadata:
      labels:
        app: web-x1
    spec:
      containers:
      - image: sagarfale/web-x1:v1
        name: web-x1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-x1
  name: web-x1-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31007
  selector:
    app: web-x1
  type: NodePort
status:
  loadBalancer: {}
